import { collectTableAudits } from './audit';
import { inferSandboxSchema } from './schemaInference';

const USER_A_ID = '11111111-1111-1111-1111-111111111111';
const USER_B_ID = '22222222-2222-2222-2222-222222222222';

export interface EmitTestsResult {
  supported: boolean;
  skipReason?: string;
  sql?: string;
}

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

/**
 * Turns a table's RLS policies into a portable, dependency-free SQL script
 * that checks read isolation against a real Postgres/Supabase database —
 * no pgTAP required. Runs entirely inside one transaction that always rolls
 * back, so it's safe against a non-empty table. Uses Supabase's real `anon`
 * and `authenticated` roles via SET LOCAL ROLE, the same pattern Supabase's
 * own SQL editor docs use for testing RLS policies interactively.
 *
 * Scope: read-isolation only (SELECT). Write-path checks (impersonation,
 * ownership hijack) are covered locally by `rls verify` / `--verify`, which
 * can safely mutate a disposable in-memory sandbox — doing the same against
 * a real table here would risk schema mismatches this tool has no way to see.
 */
export function emitRegressionTests(sql: string, table: string): EmitTestsResult {
  const normalizedTable = table.trim().toLowerCase();
  const tables = collectTableAudits([{ sourceFile: 'input', sql }]);
  const tableAudit = tables.get(normalizedTable);

  if (!tableAudit || tableAudit.policies.length === 0) {
    return { supported: false, skipReason: `no CREATE POLICY statements found for table "${table}"` };
  }

  const inferred = inferSandboxSchema(tableAudit.policies, normalizedTable);
  if (!inferred.supported) {
    return { supported: false, skipReason: inferred.reason };
  }

  const { ownerColumn, columns } = inferred;
  const booleanColumns = Object.keys(columns).filter((name) => columns[name] === 'boolean');
  const qTable = quoteIdent(normalizedTable);
  const qOwner = quoteIdent(ownerColumn);

  const seedColumns = [ownerColumn, ...booleanColumns].map(quoteIdent).join(', ');
  const rowAValues = [`'${USER_A_ID}'`, ...booleanColumns.map(() => 'false')].join(', ');
  const rowBValues = [`'${USER_B_ID}'`, ...booleanColumns.map(() => 'true')].join(', ');

  const publicFilter =
    booleanColumns.length > 0 ? ` AND NOT (${booleanColumns.map((c) => `${quoteIdent(c)} = true`).join(' OR ')})` : '';

  const identities: Array<{ label: string; role: string; uuid: string | null }> = [
    { label: 'anon', role: 'anon', uuid: null },
    { label: 'userA', role: 'authenticated', uuid: USER_A_ID },
    { label: 'userB', role: 'authenticated', uuid: USER_B_ID },
  ];

  const lines: string[] = [
    `-- Auto-generated by \`rls generate --emit-tests\` for table "${normalizedTable}".`,
    '-- Read-isolation regression check — seeds two synthetic rows, switches role/JWT',
    "-- claims per Supabase's own SQL-editor pattern for testing RLS, and asserts what",
    '-- each identity can SELECT. Everything runs inside one transaction that always',
    '-- rolls back, so it is safe to run against a real (non-empty) table.',
    '--',
    '-- NOTE: only the RLS-relevant columns below are populated. If this table has other',
    '-- NOT NULL columns without a default, add them to the INSERT statements first.',
    '--',
    '-- Run with: psql "$DATABASE_URL" -f this-file.sql   (or paste into the Supabase SQL editor)',
    '',
    'BEGIN;',
    '',
    `INSERT INTO ${qTable} (${seedColumns}) VALUES (${rowAValues});`,
    `INSERT INTO ${qTable} (${seedColumns}) VALUES (${rowBValues});`,
    '',
  ];

  for (const identity of identities) {
    lines.push(`-- Probe: ${identity.label}`);
    lines.push(`SET LOCAL ROLE ${identity.role};`);
    lines.push(
      identity.uuid
        ? `SET LOCAL request.jwt.claims = '{"sub":"${identity.uuid}","role":"authenticated"}';`
        : 'RESET request.jwt.claims;'
    );
    lines.push('DO $$');
    lines.push('DECLARE');
    lines.push('  own_visible int;');
    lines.push('  leaked int;');
    lines.push('BEGIN');
    if (identity.uuid) {
      lines.push(`  SELECT count(*) INTO own_visible FROM ${qTable} WHERE ${qOwner} = '${identity.uuid}';`);
      lines.push('  IF own_visible <> 1 THEN');
      lines.push(
        `    RAISE EXCEPTION 'FAIL [${identity.label} select-own]: expected to see their own synthetic row, saw %', own_visible;`
      );
      lines.push('  END IF;');
    }
    const otherUuid = identity.uuid === USER_A_ID ? USER_B_ID : USER_A_ID;
    lines.push(
      `  SELECT count(*) INTO leaked FROM ${qTable} WHERE ${qOwner} IN ('${USER_A_ID}', '${USER_B_ID}')` +
        `${identity.uuid ? ` AND ${qOwner} = '${otherUuid}'` : ''}${publicFilter};`
    );
    lines.push('  IF leaked > 0 THEN');
    lines.push(
      `    RAISE EXCEPTION 'FAIL [${identity.label} leak]: can see % row(s) they do not own and are not public', leaked;`
    );
    lines.push('  END IF;');
    lines.push('END $$;');
    lines.push('');
  }

  lines.push('RESET ROLE;');
  lines.push('ROLLBACK;');
  lines.push('');

  return { supported: true, sql: lines.join('\n') };
}
